#!/usr/bin/env python3
import os
import sys


def main() -> int:
    os.environ["PYTHONDONTWRITEBYTECODE"] = "1"
    sys.dont_write_bytecode = True
    from sync_bookmarks import main as run

    return run()


if __name__ == "__main__":
    raise SystemExit(main())
